# Generated by Django 4.2 on 2023-04-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time',
        ),
    ]
