# Generated by Django 4.2 on 2023-04-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_article_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
