# Generated by Django 4.2 on 2023-04-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_alter_article_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time',
        ),
    ]
