# Generated by Django 4.2 on 2023-04-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_re_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Re_Comment',
        ),
    ]
