# Generated by Django 4.2 on 2023-04-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_re_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Re_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_comments', to='app.comment')),
            ],
        ),
    ]
