# Generated by Django 4.2 on 2023-04-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_post_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='deadline'),
        ),
    ]
