# Generated by Django 4.2 on 2023-04-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deadline',
        ),
    ]
